In [78]:
# Przedstawienie danych

In [79]:
import pandas as pd
file_path = 'ccm_rul_datasett.csv'

# Try reading the CSV without interpreting quotes
data = pd.read_csv(file_path)



data.head()

,date,"workpiece_weight, tonn",steel_type,doc_requirement,cast_in_row,workpiece_slice_geometry,alloy_type,"steel_weight_theoretical, tonn","slag_weight_close_grab1, tonn","metal_residue_grab1, tonn",...,"Al, %","Ca, %","N, %","Pb, %","Mg, %","Zn, %",sleeve,num_crystallizer,num_stream,RUL
0,2020-01-05,144.9,Arm240,DOC 34028-2016,4,150x150,open,145.3,1.8,0.4,...,0.0022,0.0008,0.0085,0.0,0.0,0.0,30012261,22,4,384.0
1,2020-01-05,165.9,St3sp,Contract,10,150x150,open,166.3,1.8,0.4,...,0.0028,0.0004,0.0049,0.0,0.0,0.0,30013346,2,1,1037.0
2,2020-01-05,168.0,Arm240,DOC 34028-2016,5,150x150,open,168.4,1.8,0.4,...,0.0031,0.0011,0.0068,0.0,0.0,0.0,30012261,22,4,355.0
3,2020-01-05,170.1,St3sp,Contract,7,150x150,open,170.5,1.8,0.4,...,0.0034,0.0005,0.0051,0.0,0.0,0.0,30012261,22,4,300.0
4,2020-01-05,163.8,St3sp,Contract,12,150x150,open,164.2,1.8,0.4,...,0.0032,0.0004,0.0038,0.0,0.0,0.0,30012261,22,4,164.0

In [80]:
# Statystyka opisowa: opis zmiennych

In [81]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17503 entries, 0 to 17502
Data columns (total 57 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   date                                                         17503 non-null  object
 1   workpiece_weight, tonn                                       17503 non-null  float64
 2   steel_type                                                   17503 non-null  object
 3   doc_requirement                                              17503 non-null  object
 4   cast_in_row                                                  17503 non-null  int64
 5   workpiece_slice_geometry                                     17503 non-null  object
 6   alloy_type                                                   17503 non-null  object
 7   steel_weight_theoretical, tonn                               17503 non-null  float64
 8   slag_weight_close_grab1, tonn                                17503 non-null  float64
 9   metal_residue_grab1, tonn                                    17503 non-null  float64
 10  steel_weight, tonn                                           17503 non-null  float64
 11  residuals_grab2, tonn                                        513 non-null    float64
 12  technical_trim, tonn                                         76 non-null     float64
 13  grab1_num                                                    17232 non-null  float64
 14  steel_temperature_grab1, Celsius deg.                        17500 non-null  float64
 15  grab2_num                                                    17487 non-null  float64
 16  resistance, tonn                                             17279 non-null  float64
 17  swing_frequency, amount/minute                               17503 non-null  int64
 18  crystallizer_movement, mm                                    17503 non-null  int64
 19  alloy_speed, meter/minute                                    17503 non-null  int64
 20  water_consumption, liter/minute                              17503 non-null  int64
 21  water_temperature_delta, Celsius deg.                        17503 non-null  int64
 22  water_consumption_secondary_cooling_zone_num1, liter/minute  17503 non-null  int64
 23  water_consumption_secondary_cooling_zone_num2, liter/minute  17503 non-null  int64
 24  water_consumption_secondary_cooling_zone_num3, liter/minute  17489 non-null  float64
 25  kind                                                         15240 non-null  object
 26  quantity, tonn                                               15240 non-null  float64
 27  time_temperature_measurement1                                17503 non-null  object
 28  temperature_measurement1, Celsius deg.                       17477 non-null  float64
 29  time_temperature_measurement2                                17503 non-null  object
 30  temperature_measurement2, Celsius deg.                       17477 non-null  float64
 31  sample_time_continuous_caster                                17503 non-null  object
 32  Ce, %                                                        12073 non-null  float64
 33  C, %                                                         17503 non-null  float64
 34  Si, %                                                        17503 non-null  float64
 35  Mn,%                                                         17503 non-null  float64
 36  S, %                                                         17503 non-null  float64
 37  P, %                                                         17503 non-null  float64
 38  Cr, %                                                        17503 non-null  float64
 39  Ni, %                                                        17503 non-null  float64
 40  Cu, %                                                        17503 non-null  float64
 41  As, %                                                        17493 non-null  float64
 42  Mo, %                                                        17491 non-null  float64
 43  Nb, %                                                        17491 non-null  float64
 44  Sn, %                                                        2254 non-null   float64
 45  Ti, %                                                        17491 non-null  float64
 46  V, %                                                         17503 non-null  float64
 47  Al, %                                                        17503 non-null  float64
 48  Ca, %                                                        17503 non-null  float64
 49  N, %                                                         17503 non-null  float64
 50  Pb, %                                                        17503 non-null  float64
 51  Mg, %                                                        17503 non-null  float64
 52  Zn, %                                                        17503 non-null  float64
 53  sleeve                                                       17503 non-null  object
 54  num_crystallizer                                             17503 non-null  int64
 55  num_stream                                                   17503 non-null  int64
 56  RUL                                                          17279 non-null  float64
dtypes: float64(37), int64(10), object(10)
memory usage: 7.6+ MB

In [82]:
# Statystyka opisowa

In [83]:
data.describe()

,"workpiece_weight, tonn",cast_in_row,"steel_weight_theoretical, tonn","slag_weight_close_grab1, tonn","metal_residue_grab1, tonn","steel_weight, tonn","residuals_grab2, tonn","technical_trim, tonn",grab1_num,"steel_temperature_grab1, Celsius deg.",...,"V, %","Al, %","Ca, %","N, %","Pb, %","Mg, %","Zn, %",num_crystallizer,num_stream,RUL
count,17503.000000,17503.000000,17503.000000,1.750300e+04,17503.000000,17503.000000,513.000000,76.000000,17232.000000,17500.000000,...,17503.000000,17503.000000,17503.000000,17503.000000,17503.000000,17503.000000,17503.000000,17503.000000,17503.000000,1.727900e+04
mean,163.353867,20.138662,164.361359,1.800000e+00,0.422716,163.938643,5.771189,5.271974,6.334668,1566.878171,...,0.002477,0.002794,0.001003,0.006239,0.002217,0.000070,0.000958,12.762212,3.548934,2.085479e+05
std,5.720208,13.450384,5.153493,5.049439e-13,0.978337,5.258552,4.219523,10.132871,3.550092,23.740470,...,0.001265,0.000817,0.000523,0.001654,0.001690,0.000077,0.001178,5.463315,1.694328,1.286672e+06
min,73.779000,0.000000,126.841000,1.800000e+00,0.400000,110.835000,2.700000,0.610000,1.000000,567.000000,...,0.000100,0.001300,0.000100,0.001600,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000e+00
25%,159.744000,9.000000,160.496000,1.800000e+00,0.400000,160.096000,4.000000,0.900000,3.000000,1563.000000,...,0.001800,0.002300,0.000700,0.005100,0.000000,0.000000,0.000000,9.000000,2.000000,2.385000e+03
50%,163.296000,18.000000,163.696000,1.800000e+00,0.400000,163.296000,5.000000,1.345000,6.000000,1567.000000,...,0.002300,0.002700,0.000900,0.006400,0.002700,0.000100,0.000000,12.000000,3.000000,4.990000e+03
75%,165.900000,29.000000,166.720000,1.800000e+00,0.400000,166.320000,5.800000,1.650000,10.000000,1570.000000,...,0.003000,0.003200,0.001200,0.007400,0.003600,0.000100,0.001800,17.000000,5.000000,8.245000e+03
max,184.320000,61.000000,189.300000,1.800000e+00,50.000000,188.900000,30.000000,32.500000,12.000000,1667.000000,...,0.044900,0.019300,0.009000,0.012300,0.005300,0.001000,0.007800,24.000000,6.000000,8.473111e+06

In [84]:
# PorzÄ…dkowanie danych

In [85]:
# Sprawdzenie brakujÄ…cych danych

In [86]:
data.isnull().sum()

date                                                               0
workpiece_weight, tonn                                             0
steel_type                                                         0
doc_requirement                                                    0
cast_in_row                                                        0
workpiece_slice_geometry                                           0
alloy_type                                                         0
steel_weight_theoretical, tonn                                     0
slag_weight_close_grab1, tonn                                      0
metal_residue_grab1, tonn                                          0
steel_weight, tonn                                                 0
residuals_grab2, tonn                                          16990
technical_trim, tonn                                           17427
grab1_num                                                        271
steel_temperature_grab1, Celsius deg.                              3
grab2_num                                                         16
resistance, tonn                                                 224
swing_frequency, amount/minute                                     0
crystallizer_movement, mm                                          0
alloy_speed, meter/minute                                          0
water_consumption, liter/minute                                    0
water_temperature_delta, Celsius deg.                              0
water_consumption_secondary_cooling_zone_num1, liter/minute        0
water_consumption_secondary_cooling_zone_num2, liter/minute        0
water_consumption_secondary_cooling_zone_num3, liter/minute       14
kind                                                            2263
quantity, tonn                                                  2263
time_temperature_measurement1                                      0
temperature_measurement1, Celsius deg.                            26
time_temperature_measurement2                                      0
temperature_measurement2, Celsius deg.                            26
sample_time_continuous_caster                                      0
Ce, %                                                           5430
C, %                                                               0
Si, %                                                              0
Mn,%                                                               0
S, %                                                               0
P, %                                                               0
Cr, %                                                              0
Ni, %                                                              0
Cu, %                                                              0
As, %                                                             10
Mo, %                                                             12
Nb, %                                                             12
Sn, %                                                          15249
Ti, %                                                             12
V, %                                                               0
Al, %                                                              0
Ca, %                                                              0
N, %                                                               0
Pb, %                                                              0
Mg, %                                                              0
Zn, %                                                              0
sleeve                                                             0
num_crystallizer                                                   0
num_stream                                                         0
RUL                                                              224
dtype: int64

In [87]:
# W kolumnach: residuals_grab2, technical_trim, grab1_num, ... , Ti, RUL, znajdujÄ… siÄ™ puste wiersze.

In [88]:
# Obliczenie jaki % stanowiÄ… puste wiersze w caÅ‚oÅ›ci kolumny.

In [89]:
data.isnull().mean() * 100

date                                                            0.000000
workpiece_weight, tonn                                          0.000000
steel_type                                                      0.000000
doc_requirement                                                 0.000000
cast_in_row                                                     0.000000
workpiece_slice_geometry                                        0.000000
alloy_type                                                      0.000000
steel_weight_theoretical, tonn                                  0.000000
slag_weight_close_grab1, tonn                                   0.000000
metal_residue_grab1, tonn                                       0.000000
steel_weight, tonn                                              0.000000
residuals_grab2, tonn                                          97.069074
technical_trim, tonn                                           99.565789
grab1_num                                                       1.548306
steel_temperature_grab1, Celsius deg.                           0.017140
grab2_num                                                       0.091413
resistance, tonn                                                1.279781
swing_frequency, amount/minute                                  0.000000
crystallizer_movement, mm                                       0.000000
alloy_speed, meter/minute                                       0.000000
water_consumption, liter/minute                                 0.000000
water_temperature_delta, Celsius deg.                           0.000000
water_consumption_secondary_cooling_zone_num1, liter/minute     0.000000
water_consumption_secondary_cooling_zone_num2, liter/minute     0.000000
water_consumption_secondary_cooling_zone_num3, liter/minute     0.079986
kind                                                           12.929212
quantity, tonn                                                 12.929212
time_temperature_measurement1                                   0.000000
temperature_measurement1, Celsius deg.                          0.148546
time_temperature_measurement2                                   0.000000
temperature_measurement2, Celsius deg.                          0.148546
sample_time_continuous_caster                                   0.000000
Ce, %                                                          31.023253
C, %                                                            0.000000
Si, %                                                           0.000000
Mn,%                                                            0.000000
S, %                                                            0.000000
P, %                                                            0.000000
Cr, %                                                           0.000000
Ni, %                                                           0.000000
Cu, %                                                           0.000000
As, %                                                           0.057133
Mo, %                                                           0.068560
Nb, %                                                           0.068560
Sn, %                                                          87.122208
Ti, %                                                           0.068560
V, %                                                            0.000000
Al, %                                                           0.000000
Ca, %                                                           0.000000
N, %                                                            0.000000
Pb, %                                                           0.000000
Mg, %                                                           0.000000
Zn, %                                                           0.000000
sleeve                                                          0.000000
num_crystallizer                                                0.000000
num_stream                                                      0.000000
RUL                                                             1.279781
dtype: float64

In [90]:
# Opcje postÄ™powania z brakujÄ…cymi danymi:
    #ZastÄ…pienie staÅ‚Ä… (Å›rednia/mediana/dominanta) - <10% brakujÄ…cych danych
    #UsuniÄ™cie niekompletnego wiersza - <20% brakujÄ…cych danych
    #UsuniÄ™cie kolumny - >25% brakujÄ…cych danych

In [91]:
# Kolumny: "residuals_grab2, tonn"; "technical_trim, tonn"; "Ce, %"; "Sn, %" - posiadajÄ… wiÄ™cej niÅ¼ 25% brakujÄ…cych danych, dlatego zostanÄ… usuniÄ™te.

In [92]:
data.drop('residuals_grab2, tonn',
  axis='columns', inplace=True)

data.head()

,date,"workpiece_weight, tonn",steel_type,doc_requirement,cast_in_row,workpiece_slice_geometry,alloy_type,"steel_weight_theoretical, tonn","slag_weight_close_grab1, tonn","metal_residue_grab1, tonn",...,"Al, %","Ca, %","N, %","Pb, %","Mg, %","Zn, %",sleeve,num_crystallizer,num_stream,RUL
0,2020-01-05,144.9,Arm240,DOC 34028-2016,4,150x150,open,145.3,1.8,0.4,...,0.0022,0.0008,0.0085,0.0,0.0,0.0,30012261,22,4,384.0
1,2020-01-05,165.9,St3sp,Contract,10,150x150,open,166.3,1.8,0.4,...,0.0028,0.0004,0.0049,0.0,0.0,0.0,30013346,2,1,1037.0
2,2020-01-05,168.0,Arm240,DOC 34028-2016,5,150x150,open,168.4,1.8,0.4,...,0.0031,0.0011,0.0068,0.0,0.0,0.0,30012261,22,4,355.0
3,2020-01-05,170.1,St3sp,Contract,7,150x150,open,170.5,1.8,0.4,...,0.0034,0.0005,0.0051,0.0,0.0,0.0,30012261,22,4,300.0
4,2020-01-05,163.8,St3sp,Contract,12,150x150,open,164.2,1.8,0.4,...,0.0032,0.0004,0.0038,0.0,0.0,0.0,30012261,22,4,164.0

In [93]:
data.drop('technical_trim, tonn',
  axis='columns', inplace=True)

data.head()

,date,"workpiece_weight, tonn",steel_type,doc_requirement,cast_in_row,workpiece_slice_geometry,alloy_type,"steel_weight_theoretical, tonn","slag_weight_close_grab1, tonn","metal_residue_grab1, tonn",...,"Al, %","Ca, %","N, %","Pb, %","Mg, %","Zn, %",sleeve,num_crystallizer,num_stream,RUL
0,2020-01-05,144.9,Arm240,DOC 34028-2016,4,150x150,open,145.3,1.8,0.4,...,0.0022,0.0008,0.0085,0.0,0.0,0.0,30012261,22,4,384.0
1,2020-01-05,165.9,St3sp,Contract,10,150x150,open,166.3,1.8,0.4,...,0.0028,0.0004,0.0049,0.0,0.0,0.0,30013346,2,1,1037.0
2,2020-01-05,168.0,Arm240,DOC 34028-2016,5,150x150,open,168.4,1.8,0.4,...,0.0031,0.0011,0.0068,0.0,0.0,0.0,30012261,22,4,355.0
3,2020-01-05,170.1,St3sp,Contract,7,150x150,open,170.5,1.8,0.4,...,0.0034,0.0005,0.0051,0.0,0.0,0.0,30012261,22,4,300.0
4,2020-01-05,163.8,St3sp,Contract,12,150x150,open,164.2,1.8,0.4,...,0.0032,0.0004,0.0038,0.0,0.0,0.0,30012261,22,4,164.0

In [94]:
data.drop('Ce, %',
  axis='columns', inplace=True)

data.head()

,date,"workpiece_weight, tonn",steel_type,doc_requirement,cast_in_row,workpiece_slice_geometry,alloy_type,"steel_weight_theoretical, tonn","slag_weight_close_grab1, tonn","metal_residue_grab1, tonn",...,"Al, %","Ca, %","N, %","Pb, %","Mg, %","Zn, %",sleeve,num_crystallizer,num_stream,RUL
0,2020-01-05,144.9,Arm240,DOC 34028-2016,4,150x150,open,145.3,1.8,0.4,...,0.0022,0.0008,0.0085,0.0,0.0,0.0,30012261,22,4,384.0
1,2020-01-05,165.9,St3sp,Contract,10,150x150,open,166.3,1.8,0.4,...,0.0028,0.0004,0.0049,0.0,0.0,0.0,30013346,2,1,1037.0
2,2020-01-05,168.0,Arm240,DOC 34028-2016,5,150x150,open,168.4,1.8,0.4,...,0.0031,0.0011,0.0068,0.0,0.0,0.0,30012261,22,4,355.0
3,2020-01-05,170.1,St3sp,Contract,7,150x150,open,170.5,1.8,0.4,...,0.0034,0.0005,0.0051,0.0,0.0,0.0,30012261,22,4,300.0
4,2020-01-05,163.8,St3sp,Contract,12,150x150,open,164.2,1.8,0.4,...,0.0032,0.0004,0.0038,0.0,0.0,0.0,30012261,22,4,164.0

In [95]:
data.drop('Sn, %',
  axis='columns', inplace=True)

data.head()

,date,"workpiece_weight, tonn",steel_type,doc_requirement,cast_in_row,workpiece_slice_geometry,alloy_type,"steel_weight_theoretical, tonn","slag_weight_close_grab1, tonn","metal_residue_grab1, tonn",...,"Al, %","Ca, %","N, %","Pb, %","Mg, %","Zn, %",sleeve,num_crystallizer,num_stream,RUL
0,2020-01-05,144.9,Arm240,DOC 34028-2016,4,150x150,open,145.3,1.8,0.4,...,0.0022,0.0008,0.0085,0.0,0.0,0.0,30012261,22,4,384.0
1,2020-01-05,165.9,St3sp,Contract,10,150x150,open,166.3,1.8,0.4,...,0.0028,0.0004,0.0049,0.0,0.0,0.0,30013346,2,1,1037.0
2,2020-01-05,168.0,Arm240,DOC 34028-2016,5,150x150,open,168.4,1.8,0.4,...,0.0031,0.0011,0.0068,0.0,0.0,0.0,30012261,22,4,355.0
3,2020-01-05,170.1,St3sp,Contract,7,150x150,open,170.5,1.8,0.4,...,0.0034,0.0005,0.0051,0.0,0.0,0.0,30012261,22,4,300.0
4,2020-01-05,163.8,St3sp,Contract,12,150x150,open,164.2,1.8,0.4,...,0.0032,0.0004,0.0038,0.0,0.0,0.0,30012261,22,4,164.0

In [96]:
# Kolumny z brakujÄ…cymi danymi (>25%) zostaÅ‚y usuniÄ™te.

In [97]:
# Kolumny:  - posiadajÄ… nie wiÄ™cej niÅ¼ 20% brakujÄ…cych danych, dlatego wiersze zawiÄ™rajÄ…ce brakujÄ…ce dane zostanÄ… usuniÄ™te.

In [98]:
# Sprawdznie czy brakujÄ…ce wartoÅ›ci z kolumn: "kind" oraz "quantity, tonn" pokrywajÄ… siÄ™

In [99]:
both_na = data['kind'].isna() & data['quantity, tonn'].isna()

matching_na_count = both_na.sum()

print(f"Liczba wierszy, gdzie puste wartoÅ›ci w 'kind' pokrywajÄ… siÄ™ z pustymi wartoÅ›ciami w 'quantity': {matching_na_count}")

Liczba wierszy, gdzie puste wartoÅ›ci w 'kind' pokrywajÄ… siÄ™ z pustymi wartoÅ›ciami w 'quantity': 2263

In [100]:
# Teraz mamy pewnoÅ›Ä‡, Å¼e usuwajÄ…c te wiersze stracimy tylko 12.929212% danych.

In [101]:
data.dropna(subset=['kind', 'quantity, tonn'], inplace=True)

data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15240 entries, 0 to 17502
Data columns (total 53 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   date                                                         15240 non-null  object
 1   workpiece_weight, tonn                                       15240 non-null  float64
 2   steel_type                                                   15240 non-null  object
 3   doc_requirement                                              15240 non-null  object
 4   cast_in_row                                                  15240 non-null  int64
 5   workpiece_slice_geometry                                     15240 non-null  object
 6   alloy_type                                                   15240 non-null  object
 7   steel_weight_theoretical, tonn                               15240 non-null  float64
 8   slag_weight_close_grab1, tonn                                15240 non-null  float64
 9   metal_residue_grab1, tonn                                    15240 non-null  float64
 10  steel_weight, tonn                                           15240 non-null  float64
 11  grab1_num                                                    14976 non-null  float64
 12  steel_temperature_grab1, Celsius deg.                        15237 non-null  float64
 13  grab2_num                                                    15224 non-null  float64
 14  resistance, tonn                                             15049 non-null  float64
 15  swing_frequency, amount/minute                               15240 non-null  int64
 16  crystallizer_movement, mm                                    15240 non-null  int64
 17  alloy_speed, meter/minute                                    15240 non-null  int64
 18  water_consumption, liter/minute                              15240 non-null  int64
 19  water_temperature_delta, Celsius deg.                        15240 non-null  int64
 20  water_consumption_secondary_cooling_zone_num1, liter/minute  15240 non-null  int64
 21  water_consumption_secondary_cooling_zone_num2, liter/minute  15240 non-null  int64
 22  water_consumption_secondary_cooling_zone_num3, liter/minute  15226 non-null  float64
 23  kind                                                         15240 non-null  object
 24  quantity, tonn                                               15240 non-null  float64
 25  time_temperature_measurement1                                15240 non-null  object
 26  temperature_measurement1, Celsius deg.                       15227 non-null  float64
 27  time_temperature_measurement2                                15240 non-null  object
 28  temperature_measurement2, Celsius deg.                       15227 non-null  float64
 29  sample_time_continuous_caster                                15240 non-null  object
 30  C, %                                                         15240 non-null  float64
 31  Si, %                                                        15240 non-null  float64
 32  Mn,%                                                         15240 non-null  float64
 33  S, %                                                         15240 non-null  float64
 34  P, %                                                         15240 non-null  float64
 35  Cr, %                                                        15240 non-null  float64
 36  Ni, %                                                        15240 non-null  float64
 37  Cu, %                                                        15240 non-null  float64
 38  As, %                                                        15230 non-null  float64
 39  Mo, %                                                        15228 non-null  float64
 40  Nb, %                                                        15228 non-null  float64
 41  Ti, %                                                        15228 non-null  float64
 42  V, %                                                         15240 non-null  float64
 43  Al, %                                                        15240 non-null  float64
 44  Ca, %                                                        15240 non-null  float64
 45  N, %                                                         15240 non-null  float64
 46  Pb, %                                                        15240 non-null  float64
 47  Mg, %                                                        15240 non-null  float64
 48  Zn, %                                                        15240 non-null  float64
 49  sleeve                                                       15240 non-null  object
 50  num_crystallizer                                             15240 non-null  int64
 51  num_stream                                                   15240 non-null  int64
 52  RUL                                                          15049 non-null  float64
dtypes: float64(33), int64(10), object(10)
memory usage: 6.3+ MB

In [102]:
# PozostaÅ‚e brakujÄ…ce dane w kolumnach zastÄ…piono medianÄ… tych wartoÅ›ci.

In [103]:
columns_to_fill = ['grab1_num', 'steel_temperature_grab1, Celsius deg.', 'grab2_num', 'resistance, tonn', 'water_consumption_secondary_cooling_zone_num3, liter/minute', 'temperature_measurement1, Celsius deg.', 'temperature_measurement2, Celsius deg.', 'As, %', 'Mo, %', 'Nb, %', 'Ti, %', 'RUL']

# Dla kaÅ¼dej kolumny obliczono medianÄ™ i uzupeÅ‚niono brakujÄ…ce wartoÅ›ci
for column in columns_to_fill:
    median_value = data[column].median()
    data[column].fillna(median_value, inplace=True)

data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15240 entries, 0 to 17502
Data columns (total 53 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   date                                                         15240 non-null  object
 1   workpiece_weight, tonn                                       15240 non-null  float64
 2   steel_type                                                   15240 non-null  object
 3   doc_requirement                                              15240 non-null  object
 4   cast_in_row                                                  15240 non-null  int64
 5   workpiece_slice_geometry                                     15240 non-null  object
 6   alloy_type                                                   15240 non-null  object
 7   steel_weight_theoretical, tonn                               15240 non-null  float64
 8   slag_weight_close_grab1, tonn                                15240 non-null  float64
 9   metal_residue_grab1, tonn                                    15240 non-null  float64
 10  steel_weight, tonn                                           15240 non-null  float64
 11  grab1_num                                                    15240 non-null  float64
 12  steel_temperature_grab1, Celsius deg.                        15240 non-null  float64
 13  grab2_num                                                    15240 non-null  float64
 14  resistance, tonn                                             15240 non-null  float64
 15  swing_frequency, amount/minute                               15240 non-null  int64
 16  crystallizer_movement, mm                                    15240 non-null  int64
 17  alloy_speed, meter/minute                                    15240 non-null  int64
 18  water_consumption, liter/minute                              15240 non-null  int64
 19  water_temperature_delta, Celsius deg.                        15240 non-null  int64
 20  water_consumption_secondary_cooling_zone_num1, liter/minute  15240 non-null  int64
 21  water_consumption_secondary_cooling_zone_num2, liter/minute  15240 non-null  int64
 22  water_consumption_secondary_cooling_zone_num3, liter/minute  15240 non-null  float64
 23  kind                                                         15240 non-null  object
 24  quantity, tonn                                               15240 non-null  float64
 25  time_temperature_measurement1                                15240 non-null  object
 26  temperature_measurement1, Celsius deg.                       15240 non-null  float64
 27  time_temperature_measurement2                                15240 non-null  object
 28  temperature_measurement2, Celsius deg.                       15240 non-null  float64
 29  sample_time_continuous_caster                                15240 non-null  object
 30  C, %                                                         15240 non-null  float64
 31  Si, %                                                        15240 non-null  float64
 32  Mn,%                                                         15240 non-null  float64
 33  S, %                                                         15240 non-null  float64
 34  P, %                                                         15240 non-null  float64
 35  Cr, %                                                        15240 non-null  float64
 36  Ni, %                                                        15240 non-null  float64
 37  Cu, %                                                        15240 non-null  float64
 38  As, %                                                        15240 non-null  float64
 39  Mo, %                                                        15240 non-null  float64
 40  Nb, %                                                        15240 non-null  float64
 41  Ti, %                                                        15240 non-null  float64
 42  V, %                                                         15240 non-null  float64
 43  Al, %                                                        15240 non-null  float64
 44  Ca, %                                                        15240 non-null  float64
 45  N, %                                                         15240 non-null  float64
 46  Pb, %                                                        15240 non-null  float64
 47  Mg, %                                                        15240 non-null  float64
 48  Zn, %                                                        15240 non-null  float64
 49  sleeve                                                       15240 non-null  object
 50  num_crystallizer                                             15240 non-null  int64
 51  num_stream                                                   15240 non-null  int64
 52  RUL                                                          15240 non-null  float64
dtypes: float64(33), int64(10), object(10)
memory usage: 6.3+ MB

In [104]:
# OdstajÄ…ce wartoÅ›ci

In [105]:
# Metoda kwartylowa (IQR - Interquartile Range): Usuwanie wartoÅ›ci poza zakresem 3-krotnoÅ›ci rozstÄ™pu miÄ™dzykwartylowego.

In [106]:
""" 
import numpy as np 
import seaborn as sns
import plotly.express as px

for column in data.columns:
    fig = px.histogram(data, x=column)
    fig.show()
"""

' \nimport numpy as np \nimport seaborn as sns\nimport plotly.express as px\n\nfor column in data.columns:\n    fig = px.histogram(data, x=column)\n    fig.show()\n'

In [107]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15240 entries, 0 to 17502
Data columns (total 53 columns):
 #   Column                                                       Non-Null Count  Dtype
---  ------                                                       --------------  -----
 0   date                                                         15240 non-null  object
 1   workpiece_weight, tonn                                       15240 non-null  float64
 2   steel_type                                                   15240 non-null  object
 3   doc_requirement                                              15240 non-null  object
 4   cast_in_row                                                  15240 non-null  int64
 5   workpiece_slice_geometry                                     15240 non-null  object
 6   alloy_type                                                   15240 non-null  object
 7   steel_weight_theoretical, tonn                               15240 non-null  float64
 8   slag_weight_close_grab1, tonn                                15240 non-null  float64
 9   metal_residue_grab1, tonn                                    15240 non-null  float64
 10  steel_weight, tonn                                           15240 non-null  float64
 11  grab1_num                                                    15240 non-null  float64
 12  steel_temperature_grab1, Celsius deg.                        15240 non-null  float64
 13  grab2_num                                                    15240 non-null  float64
 14  resistance, tonn                                             15240 non-null  float64
 15  swing_frequency, amount/minute                               15240 non-null  int64
 16  crystallizer_movement, mm                                    15240 non-null  int64
 17  alloy_speed, meter/minute                                    15240 non-null  int64
 18  water_consumption, liter/minute                              15240 non-null  int64
 19  water_temperature_delta, Celsius deg.                        15240 non-null  int64
 20  water_consumption_secondary_cooling_zone_num1, liter/minute  15240 non-null  int64
 21  water_consumption_secondary_cooling_zone_num2, liter/minute  15240 non-null  int64
 22  water_consumption_secondary_cooling_zone_num3, liter/minute  15240 non-null  float64
 23  kind                                                         15240 non-null  object
 24  quantity, tonn                                               15240 non-null  float64
 25  time_temperature_measurement1                                15240 non-null  object
 26  temperature_measurement1, Celsius deg.                       15240 non-null  float64
 27  time_temperature_measurement2                                15240 non-null  object
 28  temperature_measurement2, Celsius deg.                       15240 non-null  float64
 29  sample_time_continuous_caster                                15240 non-null  object
 30  C, %                                                         15240 non-null  float64
 31  Si, %                                                        15240 non-null  float64
 32  Mn,%                                                         15240 non-null  float64
 33  S, %                                                         15240 non-null  float64
 34  P, %                                                         15240 non-null  float64
 35  Cr, %                                                        15240 non-null  float64
 36  Ni, %                                                        15240 non-null  float64
 37  Cu, %                                                        15240 non-null  float64
 38  As, %                                                        15240 non-null  float64
 39  Mo, %                                                        15240 non-null  float64
 40  Nb, %                                                        15240 non-null  float64
 41  Ti, %                                                        15240 non-null  float64
 42  V, %                                                         15240 non-null  float64
 43  Al, %                                                        15240 non-null  float64
 44  Ca, %                                                        15240 non-null  float64
 45  N, %                                                         15240 non-null  float64
 46  Pb, %                                                        15240 non-null  float64
 47  Mg, %                                                        15240 non-null  float64
 48  Zn, %                                                        15240 non-null  float64
 49  sleeve                                                       15240 non-null  object
 50  num_crystallizer                                             15240 non-null  int64
 51  num_stream                                                   15240 non-null  int64
 52  RUL                                                          15240 non-null  float64
dtypes: float64(33), int64(10), object(10)
memory usage: 6.3+ MB

In [108]:
print(data.dtypes)

date                                                            object
workpiece_weight, tonn                                         float64
steel_type                                                      object
doc_requirement                                                 object
cast_in_row                                                      int64
workpiece_slice_geometry                                        object
alloy_type                                                      object
steel_weight_theoretical, tonn                                 float64
slag_weight_close_grab1, tonn                                  float64
metal_residue_grab1, tonn                                      float64
steel_weight, tonn                                             float64
grab1_num                                                      float64
steel_temperature_grab1, Celsius deg.                          float64
grab2_num                                                      float64
resistance, tonn                                               float64
swing_frequency, amount/minute                                   int64
crystallizer_movement, mm                                        int64
alloy_speed, meter/minute                                        int64
water_consumption, liter/minute                                  int64
water_temperature_delta, Celsius deg.                            int64
water_consumption_secondary_cooling_zone_num1, liter/minute      int64
water_consumption_secondary_cooling_zone_num2, liter/minute      int64
water_consumption_secondary_cooling_zone_num3, liter/minute    float64
kind                                                            object
quantity, tonn                                                 float64
time_temperature_measurement1                                   object
temperature_measurement1, Celsius deg.                         float64
time_temperature_measurement2                                   object
temperature_measurement2, Celsius deg.                         float64
sample_time_continuous_caster                                   object
C, %                                                           float64
Si, %                                                          float64
Mn,%                                                           float64
S, %                                                           float64
P, %                                                           float64
Cr, %                                                          float64
Ni, %                                                          float64
Cu, %                                                          float64
As, %                                                          float64
Mo, %                                                          float64
Nb, %                                                          float64
Ti, %                                                          float64
V, %                                                           float64
Al, %                                                          float64
Ca, %                                                          float64
N, %                                                           float64
Pb, %                                                          float64
Mg, %                                                          float64
Zn, %                                                          float64
sleeve                                                          object
num_crystallizer                                                 int64
num_stream                                                       int64
RUL                                                            float64
dtype: object

In [109]:
object_columns = data.select_dtypes(include=['object']).columns
print(object_columns)

Index(['date', 'steel_type', 'doc_requirement', 'workpiece_slice_geometry',
       'alloy_type', 'kind', 'time_temperature_measurement1',
       'time_temperature_measurement2', 'sample_time_continuous_caster',
       'sleeve'],
      dtype='object')

In [110]:
print(data.isnull().sum())

date                                                           0
workpiece_weight, tonn                                         0
steel_type                                                     0
doc_requirement                                                0
cast_in_row                                                    0
workpiece_slice_geometry                                       0
alloy_type                                                     0
steel_weight_theoretical, tonn                                 0
slag_weight_close_grab1, tonn                                  0
metal_residue_grab1, tonn                                      0
steel_weight, tonn                                             0
grab1_num                                                      0
steel_temperature_grab1, Celsius deg.                          0
grab2_num                                                      0
resistance, tonn                                               0
swing_frequency, amount/minute                                 0
crystallizer_movement, mm                                      0
alloy_speed, meter/minute                                      0
water_consumption, liter/minute                                0
water_temperature_delta, Celsius deg.                          0
water_consumption_secondary_cooling_zone_num1, liter/minute    0
water_consumption_secondary_cooling_zone_num2, liter/minute    0
water_consumption_secondary_cooling_zone_num3, liter/minute    0
kind                                                           0
quantity, tonn                                                 0
time_temperature_measurement1                                  0
temperature_measurement1, Celsius deg.                         0
time_temperature_measurement2                                  0
temperature_measurement2, Celsius deg.                         0
sample_time_continuous_caster                                  0
C, %                                                           0
Si, %                                                          0
Mn,%                                                           0
S, %                                                           0
P, %                                                           0
Cr, %                                                          0
Ni, %                                                          0
Cu, %                                                          0
As, %                                                          0
Mo, %                                                          0
Nb, %                                                          0
Ti, %                                                          0
V, %                                                           0
Al, %                                                          0
Ca, %                                                          0
N, %                                                           0
Pb, %                                                          0
Mg, %                                                          0
Zn, %                                                          0
sleeve                                                         0
num_crystallizer                                               0
num_stream                                                     0
RUL                                                            0
dtype: int64

In [111]:
datetime_columns = data.select_dtypes(include=['datetime64']).columns
print("Kolumny z typem datetime:", datetime_columns)

Kolumny z typem datetime: Index([], dtype='object')

In [112]:
# WyÅ›wietl kolumny o typie 'object'
object_columns = data.select_dtypes(include=['object']).columns
print(object_columns)

Index(['date', 'steel_type', 'doc_requirement', 'workpiece_slice_geometry',
       'alloy_type', 'kind', 'time_temperature_measurement1',
       'time_temperature_measurement2', 'sample_time_continuous_caster',
       'sleeve'],
      dtype='object')

In [113]:
# UsuniÄ™cie niepotrzebnych kolumn
columns_to_drop = ['date', 'time_temperature_measurement1', 'time_temperature_measurement2', 'sample_time_continuous_caster']
data_cleaned = data.drop(columns=columns_to_drop)

# Kodowanie one-hot encoding dla pozostaÅ‚ych kolumn typu 'object'
data_encoded = pd.get_dummies(data_cleaned, columns=['steel_type', 'doc_requirement', 'workpiece_slice_geometry',
                                                     'alloy_type', 'kind', 'sleeve'], drop_first=True)

In [114]:
# Testowy program
"""
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score

def mape(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    non_zero_mask = y_true != 0
    
    mape_value = np.mean(np.abs((y_true[non_zero_mask] - y_pred[non_zero_mask]) / y_true[non_zero_mask])) * 100
    
    return mape_value

X = data_encoded.drop(columns=['RUL'])  # Przypisano RUL jako target
y = data_encoded['RUL']

# PodziaÅ‚ na zbiÃ³r treningowy i testowy
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model - drzewo decyzyjne
tree_model = DecisionTreeRegressor(max_depth=20, random_state=42)

tree_model.fit(X_train, y_train)

y_pred = tree_model.predict(X_test)

import numpy as np

# Testy "dobroci" modelu
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(f"RMSE: {rmse}")

r2 = r2_score(y_test, y_pred)
print(f"R^2: {r2}")

mape_result = mape(y_test, y_pred)
print(f"MAPE: {mape_result}%")
"""

'\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeRegressor\nfrom sklearn.metrics import mean_squared_error, r2_score\n\ndef mape(y_true, y_pred):\n    y_true, y_pred = np.array(y_true), np.array(y_pred)\n    non_zero_mask = y_true != 0\n    \n    mape_value = np.mean(np.abs((y_true[non_zero_mask] - y_pred[non_zero_mask]) / y_true[non_zero_mask])) * 100\n    \n    return mape_value\n\nX = data_encoded.drop(columns=[\'RUL\'])  # Przypisano RUL jako target\ny = data_encoded[\'RUL\']\n\n# PodziaÅ‚ na zbiÃ³r treningowy i testowy\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# Model - drzewo decyzyjne\ntree_model = DecisionTreeRegressor(max_depth=20, random_state=42)\n\ntree_model.fit(X_train, y_train)\n\ny_pred = tree_model.predict(X_test)\n\nimport numpy as np\n\n# Testy "dobroci" modelu\nmse = mean_squared_error(y_test, y_pred)\nrmse = np.sqrt(mse)\nprint(f"RMSE: {rmse}")\n\nr2 = r2_score(y_test, y_pred)\nprint(f"R^2: {r2}")\n\nmape_result = mape(y_test, y_pred)\nprint(f"MAPE: {mape_result}%")\n'

In [115]:
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, make_scorer, r2_score
import numpy as np

def root_mean_squared_error(y_true, y_pred):
    
    return np.sqrt(mean_squared_error(y_true, y_pred))

def mape(y_true, y_pred):
    
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    non_zero_mask = y_true != 0
    return np.mean(np.abs((y_true[non_zero_mask] - y_pred[non_zero_mask]) / y_true[non_zero_mask])) * 100

# Przypisano RUL jako target
X = data_encoded.drop(columns=['RUL'])  
y = data_encoded['RUL']

# PodziaÅ‚ na zbiÃ³r treningowy i testowy
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# WybÃ³r modelu - drzewo decyzyjne
tree_model = DecisionTreeRegressor(max_depth=30, random_state=42)

tree_model.fit(X_train, y_train)

y_pred = tree_model.predict(X_test)

# Sprawdzanie "dobroci" modelu
rmse = root_mean_squared_error(y_test, y_pred)
print(f"RMSE: {rmse}")

# R^2
r2 = r2_score(y_test, y_pred)
print(f"R^2: {r2}")

# MAPE
mape_result = mape(y_test, y_pred)
print(f"MAPE: {mape_result}%")

# K-krotna walidacja modelu
kf = KFold(n_splits=10, shuffle=True, random_state=42)
rmse_scorer = make_scorer(root_mean_squared_error, greater_is_better=False)
mape_scorer = make_scorer(mape, greater_is_better=False)

# Wyniki kroswalidacji
rmse_scores = cross_val_score(tree_model, X, y, cv=kf, scoring=rmse_scorer)
print(f"Average RMSE (10-fold CV): {np.mean(np.abs(rmse_scores)):.2f}, Standard Deviation RMSE: {np.std(rmse_scores):.2f}")

r2_scores = cross_val_score(tree_model, X, y, cv=kf, scoring='r2')
print(f"Average R^2 (10-fold CV): {np.mean(r2_scores):.2f}, Standard Deviation R^2: {np.std(r2_scores):.2f}")

mape_scores = cross_val_score(tree_model, X, y, cv=kf, scoring=mape_scorer)
print(f"Average MAPE (10-fold CV): {np.mean(np.abs(mape_scores)):.2f}%, Standard Deviation MAPE: {np.std(mape_scores):.2f}%")

RMSE: 265763.0361250112
R^2: 0.9572399984785535
MAPE: 14.276505025174895%
Average RMSE (10-fold CV): 217045.99, Standard Deviation RMSE: 118447.54
Average R^2 (10-fold CV): 0.96, Standard Deviation R^2: 0.03
Average MAPE (10-fold CV): 55.94%, Standard Deviation MAPE: 54.51%

In [116]:
# C.D.N.